project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Presentation.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

